#!/bin/bash

NB_SESSIONS=$1
ABSPATH=$(readlink -f $0)
ABSDIR=$(dirname $ABSPATH)

if [ -z "${NB_SESSIONS##*[!0-9]*}" ]; then
  echo "$NB_SESSIONS is not a number";
  NB_SESSIONS=1
fi


for ((i=1;i<=NB_SESSIONS;i++)); do
  notify-send --icon="$HOME/Pictures/work.png" "Pomodo" "Work session starting"
  $ABSDIR/timer 25
  notify-send --icon="$HOME/Pictures/rest.png" "Pomodo" "Rest session starting"
  $ABSDIR/timer 5
done
