ZDOTDIR=$HOME/dotfiles-pierrot/zsh-conf

export EDITOR="nvim"
export HISTFILE=${ZDOTDIR}/.zsh_history
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:$HOME/.local/bin/"
